# based on
# https://askubuntu.com/a/1142276

export USER=NWJS_DMG_REPLACE_CURRENT_USER

dd if=/dev/zero of="NWJS_DMG_REPLACE_TARGET" bs=1M count=NWJS_DMG_REPLACE_SOURCE_SIZE status=progress
mkfs.hfsplus -v "NWJS_DMG_REPLACE_VOLUME_NAME" "NWJS_DMG_REPLACE_TARGET"

mkdir -pv "/tmp/NWJS_DMG_REPLACE_FILENAME"
mount -o loop "NWJS_DMG_REPLACE_TARGET" "/tmp/NWJS_DMG_REPLACE_FILENAME"
cp -a NWJS_DMG_REPLACE_SOURCE_DIRECTORY/* "/tmp/NWJS_DMG_REPLACE_FILENAME"
umount "/tmp/NWJS_DMG_REPLACE_FILENAME"

chown $USER:$USER "NWJS_DMG_REPLACE_TARGET"
